name: gateway-hub

services:
  nginx:
    build:
      context: .
    env_file:
      - .env
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ${SSL_VOLUME_PATH}
      - nginx_logs:/var/log/nginx
    environment:
      APP_DOMAIN: ${APP_DOMAIN}
      SSL_CERTIFICATE: ${SSL_CERTIFICATE:-/etc/nginx/certs/fullchain.pem}
      SSL_CERTIFICATE_KEY: ${SSL_CERTIFICATE_KEY:-/etc/nginx/certs/privkey.pem}
      PORTAL_HOST: ${PORTAL_HOST}
      MAPALAB_HOST: ${MAPALAB_HOST}
      ACERVO_HOST: ${ACERVO_HOST}
      ACERVO_CONSOLE_HOST: ${ACERVO_CONSOLE_HOST}
      MARIACHI_HOST: ${MARIACHI_HOST}
      GEOSERVER_HOST: ${GEOSERVER_HOST}
      HUACHICOL_HOST: ${HUACHICOL_HOST}
      GTM_ID: ${GTM_ID}
      BASIC_AUTH_USER: ${BASIC_AUTH_USER}
      BASIC_AUTH_PASS: ${BASIC_AUTH_PASS}
    networks:
      - iieg-network
    restart: unless-stopped

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx-exporter
    command:
      - '--nginx.scrape-uri=http://nginx:8080/stub_status'
    networks:
      - iieg-network
    depends_on:
      - nginx
    restart: unless-stopped

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail/promtail-config.yml:/etc/promtail/config.yml
      - nginx_logs:/var/log/nginx:ro
    command: -config.file=/etc/promtail/config.yml -config.expand-env=true
    environment:
      LOKI_URL: ${LOKI_URL:-http://loki:3100}
    networks:
      - iieg-network
    depends_on:
      - nginx
    restart: unless-stopped

networks:
  iieg-network:
    external: true

volumes:
  nginx_logs:
